### ISSUE TITLE
关于msi b550迫击炮以及msi x570 主板在安装mac os12.1的问题

### ISSUE THREAD

**Issue by alayyyy** [Miracle-Sakuno/General-EFI-for-OpenCore-Config#1]
我们尝试在微星b550迫击炮和微星x570主板上使用5系CPU可用的bios（如v17）安装12.1的时候遇到了以下问题
1.  带WiFi的主板必须在主板禁用WiFi后才能进入安装，哪怕该EFI在11.6时可以正常驱动
2.  在安装过程中无法读取到任何一块硬盘，哪怕该efi在11.6时可以正常安装
3. 使用该bios哪怕在win下也看不到pcie设备的路径

我们猜测是微星的bios导致了pcie设备的异常，希望帮助

**Comment by Miracle-Sakuno** [comment]
请尝试回退至较早版本的BIOS，但较早版本BIOS无法使用5000系CPU。
似乎确实是微星BIOS的问题，目前没有已知解决方法。
3000系CPU使用较早版本BIOS是正常的。
只能等待微星BIOS工程师解决这个问题。
目前能做的只有：
1.更换Zen2处理器
2.更换非微星主板
3.停留在Big Sur
